Added permisinon tx propagation after creating new network
MrLutik/kira2.0 pull request #146
Opened 2023-07-02 18:06 UTC by PeepoFrog

2023-07-03 10:37 UTC, andrsj requested changes

2023-07-03 10:37 UTC, andrsj commented on internal/manager/sekaid.go
> +		log.Errorf("error when checking tx:  %s  Command: %s\n", transactionHash, command)
Where is the `err` in error log?

2023-07-03 10:37 UTC, andrsj commented on internal/manager/sekaid.go
> +	log.Printf("\n\nout:\n %s\nCheckTransactionStatus: \n %v \n", string(out), data)
Maybe output `data` after `Unmarshal`?

2023-07-03 10:37 UTC, andrsj commented on internal/manager/sekaid.go
> +	command := fmt.Sprintf("sekaid keys show validator --keyring-backend=test --home=%s", sekaidHome)
`sekaid keys show validator --home=/root/.sekai --keyring-backend=test -a`
Return only address

2023-07-03 10:37 UTC, andrsj commented on internal/manager/sekaid.go
> +	command := fmt.Sprintf("sekaid keys show validator --keyring-backend=test --home=%s", sekaidHome)
You can check this for reference how I did it, instead or Unmarshaling yaml
https://github.com/MrLutik/kira2.0/blob/development/internal/monitoring/sekaid.go#L16
Or keep how you did

2023-07-03 10:37 UTC, andrsj commented on internal/manager/sekaid.go
> +	log.Println(key[0].Address)
`"validator address: %v"`

2023-07-03 10:37 UTC, andrsj commented on internal/types/TransactionQuery.go
> +type Data struct {
Data of what? It's hard to recognize for what data sctruct is used for

2023-07-03 10:37 UTC, andrsj commented on internal/types/types.go
> +	PermZero = 0
What about 
```
PermZero = iota // no-op permission
PermSetPermissions // the permission that allows to Set Permissions to other actors
. . .
```

2023-07-03 10:37 UTC, andrsj commented on internal/types/types.go
> +type Key struct {
`SekaidKey` is much better

2023-07-03 10:37 UTC, andrsj commented on internal/types/TransactionQuery.go
> +type Events struct {
Where this struct is used? If in `Data` struct the zero interface is

2023-07-03 10:37 UTC, andrsj commented on internal/types/TransactionQuery.go
> +type Logs struct {
The same

2023-07-03 10:37 UTC, andrsj commented on internal/types/TransactionQuery.go
> +type Tx struct {
The same

2023-07-03 10:37 UTC, andrsj commented on internal/manager/sekaid.go
> +	command := fmt.Sprintf(`sekaid tx customgov permission whitelist --from %s --keyring-backend=test --permission=%v --addr=%s --chain-id=testnet-1 --home=%s --fees=100ukex --yes --broadcast-mode=async
Hardcode `--chain-id=testnet-1`

2023-07-03 10:37 UTC, andrsj commented on internal/types/types.go
> +	Mnemonic string `yaml:"mnemonic"`
You don't need all of these field

2023-07-03 12:56 UTC, PeepoFrog commented on internal/manager/sekaid.go
> +	command := fmt.Sprintf("sekaid keys show validator --keyring-backend=test --home=%s", sekaidHome)
> You can check this for reference how I did it, instead or Unmarshaling yaml https://github.com/MrLutik/kira2.0/blob/development/internal/monitoring/sekaid.go#L16 Or keep how you did

we can rework this func so it will return whole struct and then we will use specific values from it?

2023-07-04 10:43 UTC, andrsj requested changes

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +	return nil
It's a good idea to add permission check:
https://github.com/KiraCore/kira/blob/master/workstation/launch/await-validator-init.sh#L133

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +const timeWaitBetweenBlocks = 10700
`time.Milliseconds * 10700` is much better

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +
Add more one constant `validatorName = "validator"` and use it

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +		log.Printf("\n\n\nAdding permision %v, aprx wait 20sec\n", perm)
Print the time duration, instead of "20sec"

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +	log.Printf("\n\nout:\n %s\nCheckTransactionStatus: \n %v \n", string(out), data)
`%+v` better

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +	log.Printf("\n\nout:\n %s\nCheckTransactionStatus: \n %v \n", string(out), data)
We need to ask Eugene about this format

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +	log.Printf("GivePermissionToAddress: \n %v \n", data)
Do not repeat the JSONs of TX
Print unmarshaled JSON once,
if it fails to unmarshal - print log error and string output

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +	log.Printf("\n\nout:\n %s\nCheckTransactionStatus: \n %v \n", string(out), data)
Do not repeat the JSONs of TX
Print unmarshaled JSON once,
if it fails to unmarshal - print log error and string output

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +	log.Printf("GivePermissionToAddress: \n %v \n", data)
for structures - use `%+v` for better output of structs

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
> +const timeWaitBetweenBlocks = 10700
We need to discuss it with Eugene about the time between blocks, maybe we can exclude the time to config, which we can use to set timeout for network + this constant which we use

2023-07-04 10:43 UTC, andrsj commented on internal/manager/sekaid.go
>  	DockerManager          *docker.DockerManager
I suppose it can be private field

2023-07-05 06:47 UTC, merged