Dev/init start stop
MrLutik/kira2.0 pull request #171
Opened 2023-12-27 11:40 UTC by PeepoFrog

2023-12-28 02:58 UTC, andrsj requested changes

2023-12-28 02:58 UTC, andrsj commented on internal/config/configFileController/configFileController.go
> +		DataPathInVolume:    volumeName + ":/data",
`DataPathInVolume` is not correct name for this variable
It would be better call something like `volumeMountPoint` and instead to get it like a separate field - make method with `getVolumeMountPoint` which return formatted string `%s:%s`. Additionally, we don't need to have additional variable `volumeName` and we can pass both separatly: `VolumeName` and `VolumeMountPath`

2023-12-28 02:58 UTC, andrsj commented on internal/docker/container.go
> +		if err != nil {
Which `err` do you want to check?

2023-12-28 02:58 UTC, andrsj commented on internal/manager/cli/cli.go
> +	initNode "github.com/mrlutik/kira2.0/internal/manager/cli/commands/init"
Why can't you leave the `initnode` or `nodeinit` like a package name?

2023-12-28 02:58 UTC, andrsj commented on internal/manager/cli/commands/init/init.go
> +}
Unused - there is no usage of this - can be skipped

2023-12-28 02:58 UTC, andrsj commented on internal/manager/cli/commands/start/start.go
> +
We use GIT, if we have to return back - just move your HEAD to specific commit

2023-12-28 02:58 UTC, andrsj commented on internal/docker/container.go
> +		err = dm.Cli.VolumeRemove(ctx, kiraCfg.VolumeName, true)
Do we need to remove Volume and its content?

2023-12-28 09:05 UTC, PeepoFrog commented on internal/docker/container.go
> +		err = dm.Cli.VolumeRemove(ctx, kiraCfg.VolumeName, true)
yes

2023-12-28 16:34 UTC, andrsj requested changes

2023-12-28 16:34 UTC, andrsj commented on internal/config/configFileController/configFileController.go
> +		SekaiVersion:        "latest	", // or v0.3.32 or latest
`Error fetching latest release: parse "repos/KiraCore/sekai/releases/tags/latest\t": net/url: invalid control character in URL`

There is an extra character `\t`

2023-12-28 16:34 UTC, andrsj commented on internal/config/configFileController/configFileController.go
> +		VolumeMoutPath:      ":/data",
`Error response from daemon: invalid mode: /data`

There is an extra `:` symbol, because we have this symbol in method already

2023-12-28 16:34 UTC, andrsj commented on internal/config/kira.go
> +	VolumeMoutPath      string
Comment about this?

2023-12-28 16:34 UTC, andrsj commented on internal/manager/init.go
> +// }
What is the purpose of keeping these comments?

2023-12-28 16:34 UTC, andrsj commented on internal/manager/init.go
> +	// }
And this...

2023-12-28 16:34 UTC, andrsj commented on internal/manager/init.go
> +	// }
And this...

2023-12-28 16:34 UTC, andrsj commented on internal/manager/interx.go
> +// }
And this)))

2023-12-29 09:33 UTC, andrsj commented on internal/manager/cli/commands/init/join/join.go
> +	containerManager.CleanupContainersAndVolumes(ctx, cfg)
Missed error handling

2023-12-29 09:33 UTC, andrsj commented on internal/manager/cli/commands/init/join/join.go
> +	time.Sleep(cfg.TimeBetweenBlocks + time.Second)
It would be better to add LOG about awaiting

2023-12-29 09:33 UTC, andrsj commented on internal/manager/interx.go
> +// }
This still exists

2024-01-02 11:53 UTC, merged